### ISSUE TITLE
`shock upgrade` doesn't work

### ISSUE THREAD

**Issue by csells** [Flutter-Bounty-Hunters/static_shock#26]
If I'm told there's a new version and use `shock upgrade` like so:

```sh
shock upgrade
Checking for newer versions of static_shock_cli...
New version of static_shock_cli is available: 0.1.0-dev.49 -> 0.0.1-dev.5
Updating your static_shock_cli package to version 0.0.1-dev.5...
Done upgrading static_shock_cli. Your current version is 0.1.0-dev.49.
```

then I'm told that I've upgraded to the current version and future `shock` commands indicate that I haven't upgraded:

```sh
Checking for newer versions of static_shock_cli...
New version of static_shock_cli is available: 0.1.0-dev.49 -> 0.0.1-dev.5
```

Perhaps this has to do with how the versions are compared?

**Comment by matthew-carroll** [comment]
Did you first activate a local repo version? If you explicitly activate `0.0.1-dev.4` and then upgrade, does it work?

It could be a version number thing, as you say, but we're using the same package to check for updates, as we are to run the update, so it would be odd to say an update is available, but then think there's no update.

It could also be an issue with local repo vs global activation. Maybe that package doesn't know how to move the activation from a local repo to a pub cache package?

**Comment by csells** [comment]
> Did you first activate a local repo version?

Yes. I used `dart pub global activate static_shock_cli` as per the instructions.

> If you explicitly activate 0.0.1-dev.4 and then upgrade, does it work?

When I do `dart pub global activate static_shock_cli 0.0.1-dev.4`, I lose the `upgrade` option and, I assume, the version checking itself.

**Comment by matthew-carroll** [comment]
Ok, let's investigate this issue when we release `0.0.1-dev.6` so that we can be sure about the nature of the problem.

**Comment by csells** [comment]
Looking at the code in `pub_updater`, it has [its own version checking](https://github.com/VeryGoodOpenSource/pub_updater/blob/d003cb2ac523139ba770eb5bb05153eff125c572/lib/src/pub_updater.dart#L34) that's separate from the code in `dart pub global activate`, which [`pub_updater` executes](https://github.com/VeryGoodOpenSource/pub_updater/blob/d003cb2ac523139ba770eb5bb05153eff125c572/lib/src/pub_updater.dart#L53) to do the actual update.

I'm guessing that their version comparison algorithms are different, which is causing the discrepancy.

**Comment by csells** [comment]
Some more data on the latest version:

```sh
$ shock upgrade
Checking for newer versions of static_shock_cli...
New version of static_shock_cli is available: 0.1.0-dev.50 -> 0.0.1-dev.5
Updating your static_shock_cli package to version 0.0.1-dev.5...
Done upgrading static_shock_cli. Your current version is 0.1.0-dev.50.

$ shock version
Your current version of static_shock_cli is: 0.1.0-dev.50
Checking for newer versions of static_shock_cli on Pub...
A new version is available: 0.1.0-dev.50 -> 0.0.1-dev.5
```

The way I got from 0.1.0-dev.49 -> 0.0.1-dev.50 was a manual call to `dart pub global activate static_shock_cli`.

**Comment by MarkOSullivan94** [comment]
Had something similar happen with v0.0.5 

<img width="516" alt="Screenshot 2024-07-27 at 16 47 04" src="https://github.com/user-attachments/assets/8d29b48b-fb26-4af6-a7e4-af72d5e69086">

Thought this behaviour was strange. I expected either an error to tell me the upgrade didn't work or a success message to let me know it successfully upgrade.

**Comment by matthew-carroll** [comment]
@MarkOSullivan94 I've been struggling to understand to what extent these upgrade issues are on the Static Shock side vs the Dart Pub side. For example, I've discovered that during development, I have to manually delete the CLI package's `.snapshot` file to re-activate with an updated version. 

I see that your case is dealing with non-development activation/upgrade. It's still unclear to me there where the problem is really coming from.

> I expected either an error to tell me the upgrade didn't work or a success message to let me know it successfully upgrade.

Correct me if I'm wrong, but your screenshot output looks like it's what would be expected, except with the specific problem that your attempt to upgrade didn't actually upgrade the package, right?

My guess is that the implementation believes that the upgrade worked, which is why you didn't get an error message, but somehow it didn't work, which is why the final version number isn't the latest. Part of this difficulty is that when you invoke `shock`, that actual binary that's run is determined by Pub. So if Pub, for whatever reason, retains the binary for `v0.0.5`, then the `upgrade` command appears to work, while Pub effectively prevents it.

Please let me know if you're able to get the CLI upgraded, and what it took to do that. In my case, when I've run into these difficulties, I've had to go into my `.pub-cache` directory and manually delete all the versions of `static_shock_cli` in there.

**Comment by MarkOSullivan94** [comment]
> Correct me if I'm wrong, but your screenshot output looks like it's what would be expected, except with the specific problem that your attempt to upgrade didn't actually upgrade the package, right?

It's not what I expected as this line here doesn't make sense.

> Done upgrading static_shock_cli. Your current version is 0.0.5. 

How could you know it's done upgrading static_shock_cli if the version hasn't changed? 

Either it's done upgrading the package or it failed and the current version is the same.

**Comment by MarkOSullivan94** [comment]
Ok I've identified the issue.

This has came through me using an old version of Flutter / Dart through [fvm](https://fvm.app/) and when I upgraded, it installed static_shock v0.0.8 for me instead of v0.0.5 which was happening previously.

The old version I was using: 

```
Flutter 3.16.9 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 41456452f2 (6 months ago) • 2024-01-25 10:06:23 -0800
Engine • revision f40e976bed
Tools • Dart 3.2.6 • DevTools 2.28.5
```

This is the newer version of Flutter which I switched to and was able to install the latest 

```
Flutter 3.22.0-35.0.pre • channel [user-branch] • unknown source
Framework • revision ddd6c86950 (2 months ago) • 2024-05-14 22:00:17 -0400
Engine • revision d35a1a603c
Tools • Dart 3.5.0 (build 3.5.0-154.0.dev) • DevTools 2.36.0-dev.5
```

However I did some more testing, when I installed v0.0.5 with the old version of Flutter and then switched to the newer version and tried an upgrade, it told me my current version was v0.0.5 but when I executed `shock version` I was in fact upgraded to v0.0.8

<img width="533" alt="Screenshot 2024-07-27 at 18 55 53" src="https://github.com/user-attachments/assets/36da3d3b-a828-4531-b606-a9c2fd6e01c6">

There's something going wrong with the `upgrade` command from v0.0.5, hopefully it no longer exists on v0.0.8 but if it does I hope all of this information helps you find a fix for it.

**Comment by matthew-carroll** [comment]
@MarkOSullivan94 since you got it fixed, let's assume it's OK. But if you see this again with future versions, please come back and post your current version, the version you're upgrading to, and your Dart and Flutter versions at that moment. Then I can try to repro that exact issue on my end.

**Comment by bkbonner** [comment]
I just installed static-shock and it looks like the upgrader isn't working:

```
% shock upgrade
Checking for newer versions of static_shock_cli...
New version of static_shock_cli is available: 0.0.8 -> 0.0.9
Updating your static_shock_cli package to version 0.0.9...
Done upgrading static_shock_cli. Your current version is 0.0.8.
% shock version
Your current version of static_shock_cli is: 0.0.8
A new version is available: 0.0.8 -> 0.0.9
Run `shock upgrade` to upgrade to the latest version.
```

**Comment by matthew-carroll** [comment]
Thanks for reporting this. I'll try to repro, but this has been a flaky issue that seems tied to code outside of our package. I'll see if I can find something.

**Comment by bkbonner** [comment]
Let me know what I can do to help.   Hopefully having the same environment
will help in reproducing it.
